Make stand-alone Spring work
Due to recent changes the stand-alone Spring threw an error about
a missing attribute `n1ql_workers`:

   AttributeError: 'WorkloadSettings' object has no attribute 'n1ql_workers'

Adding a default value of `0` to the settings, solve that problem.

Change-Id: I06c11a0bac57f53062f542a6224cfefaf73d24c3
Reviewed-on: http://review.couchbase.org/51631
Reviewed-by: Michael Wiederhold <mike@couchbase.com>
Tested-by: Volker Mische <volker.mische@gmail.com>